### ISSUE TITLE
🐛 输出文件名重复时，现有文件会被覆写

### ISSUE THREAD

**Issue by sirius422** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#107]
### 当前不足

在测试prompt效果或者vibe transfer参数效果的时候，通常会固定seed来生成图片，`save_image()`似乎没有考虑到这一点，导致save的时候会直接覆盖现有文件

### 建议内容

- 在文件名中加入Timestamp来避免重复
- 类似comfyui那样，在文件名后面以{seed}-None-None-0001.png这样的计数器格式保存文件

**Comment by zhulinyv** [comment]
将会在下次更新后修复

**Comment by zhulinyv** [comment]
临时修复一下, 文件保存时会在种子后添加随机字符串, 例如: 123456789qY42gH_None_None.png

计数器将在重构保存名称后更新, 将会实现自定义文件名配置, 可选配置例如: {seed}-{time}-{number}...
