### ISSUE TITLE
🐛 ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

### ISSUE THREAD

**Issue by zhulinyv** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#44]
### 确认

- 我的版本已更新到最新，且已尝试运行 `pip install -r requirements.txt` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows
- Python版本: 3.10.11

### 问题描述

启动后无法打开 http://127.0.0.1:11451

### 问题截图

![c96e6e1b3196a7245a8e599e8b30aca5](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/assets/66541860/7f600042-c662-498d-9cc8-5ea8defe25c9)

### 复现步骤

运行 run.bat 启动 webui

### 解决方案

**方法一**: 检查电脑的代理软件模式, 例如: v2ray 用户需要将模式设置为 pac 模式启动; clash 用户需要将模式设置为规则模式启动

**方法二**: 用记事本等文本编辑器打开 .env 文件, 找到 `share=False` 改为 `share=True`

**Comment by Accurio** [comment]
### 原因

设置了系统代理时，由于 Gradio 使用的 HTTPX 库不支持系统代理排除列表，HTTPX 会将对 `localhost` 和 `127.0.0.1/8` 的请求发至代理服务器；当代理服务器无法访问客户端发布的 Gradio 网站时，`networking.url_ok(self.local_url)` 会返回 `False` 并抛出 `ValueError: When localhost is not accessible, a shareable link must be created.` 错误。

### 解决方案

使用 `urllib.request.getproxies()` 获取代理服务器配置，通过 `os.environ` 设置代理服务器和代理排除列表。

```Python
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["HTTP_PROXY"]  = os.environ["http_proxy"]  = proxies["http"]
os.environ["HTTPS_PROXY"] = os.environ["https_proxy"] = proxies["https"]
os.environ["NO_PROXY"]    = os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
```

**Comment by zhulinyv** [comment]
> ### 原因
> 设置了系统代理时，由于 Gradio 使用的 HTTPX 库不支持系统代理排除列表，HTTPX 会将对 `localhost` 和 `127.0.0.1/8` 的请求发至代理服务器；当代理服务器无法访问客户端发布的 Gradio 网站时，`networking.url_ok(self.local_url)` 会返回 `False` 并抛出 `ValueError: When localhost is not accessible, a shareable link must be created.` 错误。
> 
> ### 解决方案
> 使用 `urllib.request.getproxies()` 获取代理服务器配置，通过 `os.environ` 设置代理服务器和代理排除列表。
> 
> ```python
> import os
> from urllib.request import getproxies
> 
> proxies = getproxies()
> os.environ["HTTP_PROXY"]  = os.environ["http_proxy"]  = proxies["http"]
> os.environ["HTTPS_PROXY"] = os.environ["https_proxy"] = proxies["https"]
> os.environ["NO_PROXY"]    = os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
> ```

已将你设置为受理人, 可以 fork 本项目修改代码后发起 pr

**Comment by zhulinyv** [comment]
已添加并测试通过
