### ISSUE TITLE
✨可以加入一个自定义生成分辨率的选项吗

### ISSUE THREAD

**Issue by SakanakoChan** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#79]
### 当前不足

目前只能用官网模板提供的那几套分辨率，但是官网是支持自定分辨率生成的

### 建议内容

能否允许在生成分辨率的一栏自定分辨率>_<

**Comment by zhulinyv** [comment]
可以的, 将在近期更新. 但需要注意的是, 官网在自定义设置分辨率后, 会判断长宽是否能被 64 除尽. 若不能除尽, 会调整为最靠近 64 倍数的一个数值, 例如: 当输入 12x111 时, 会自动调整为 64x128, 因此我也会做同样的处理, 否则返回 500 服务端无法解析的问题.

**Comment by zhulinyv** [comment]
已更新, 2.20.2
