### ISSUE TITLE
✨ 启动时各界面参数遵循默认配置

### ISSUE THREAD

**Issue by CO0l-github** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#85]
### 确认

- 我的版本已更新到最新，且已尝试运行 `pip install -r requirements.txt` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: 
- Python版本:  3.11.7

### 问题描述

文生图修改配置后配置被记录在了.env文件中，也在配置设置界面中可以看到，但启动项目时没有使用修改后的配置，依旧是默认配置。除此以外，是否可以提供默认提示词的修改？目前，我怀疑是main.py里许多变量初始化时没有使用env变量的值，如text2image_scale，参数value直接设为了5而非env.scale。如果有问题的话非常抱歉，最后感谢作者辛勤付出做出的实用项目。

### 问题截图

![image](https://github.com/user-attachments/assets/6fed2f73-3e63-4d47-a4cb-39576750d818)
![image](https://github.com/user-attachments/assets/74ca6123-b580-4200-b8ee-011e5fbf4e5d)

### 复现步骤

修改配置设置中文生图的设置后重启项目

**Comment by zhulinyv** [comment]
配置设置中的各种参数仅在**不能在页面中单独调整的功能**中有效, 例如: 随机蓝图, 随机图片, 随机vibe 等.

下次更新后文生图, 图生图, 局部重绘等界面启动时将遵循默认配置.

**Comment by zhulinyv** [comment]
已更新: https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/commit/39f5f300d0d960010f366ff80bcd7416a3e21079
