### ISSUE TITLE
✨colorize能做批量处理吗

### ISSUE THREAD

**Issue by timenb123** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#94]
目前我看到colorize没有，之后能做这个吗？

**Comment by zhulinyv** [comment]
可以做, 批处理的时候 prompt 是要保持固定吗

**Comment by timenb123** [comment]
> 可以做, 批处理的时候 prompt 是要保持固定吗

是的，个人想对一组连续的图片做上色，prompt固定就行；
（不固定的话估计适用于特殊的图片处理吧，那种估计不需要批量）

**Comment by zhulinyv** [comment]
已更新, 但我尚未测试, 有问题请及时汇报

**Comment by timenb123** [comment]
好的，感谢！
